name = "api-svenlaa-com"
main = "src/index.ts"
compatibility_date = "2024-12-27"

[[d1_databases]]
binding = "db"
database_name = "api-svenlaa-com"
database_id = "dbf1ae5e-fbfe-41f7-822b-afcb9b63c989"
